config/routes.rb
Rails.application.routes.draw do
  resources :apartments
  resources :buildings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :building
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :apartments
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: %i[ show edit update destroy ]

  # GET /apartments or /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1 or /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments or /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: "Apartment was successfully created." }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1 or /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: "Apartment was successfully updated." }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1 or /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: "Apartment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
      @buildings = Building.all
    end

    # Only allow a list of trusted parameters through.
    def apartment_params
      params.require(:apartment).permit(:apartment_number, :building_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: %i[ show edit update destroy ]

  # GET /buildings or /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1 or /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings or /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: "Building was successfully created." }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: "Building was successfully updated." }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: "Building was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:name, :address, :city)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/apartments/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(model: p_apartment) do |form| %>
      <% if p_apartment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(p_apartment.errors.count, "error") %> No se ha podido guardar este departamento:</h2>

          <ul>
            <% p_apartment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label "Número de departamento", class:'form-label' %>
        <%= form.text_field :apartment_number, class: 'form-control' %>
      </div>

      <!--
      <div class="mb-3">
        <%= form.label 'ID Edificio', class:'form-label' %>
        <%= form.text_field :building_id, class:'form-control' %>
      </div>
      -->

      <div class="mb-3">
        <%= form.label :building_id %>
        <%= form.select :building_id,
        options_from_collection_for_select(@buildings, :id, :name, p_apartment.building_id),
        {include_blank: "Selecciona el edificio del departamento"},
        class: 'form-select'
        %>
      </div>

      <div class="mb-3 text-end">
        <%= link_to "Cancelar", apartments_path, class: 'btn btn-light mr-3' %>
        <%= form.submit 'Registrar', class: 'btn btn-primary' %>
      </div>

    <% end %>
  </div>
</div>

app/views/apartments/edit.html.erb
<h1>Editando Departamento</h1>

<%= render 'form', p_apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-body">
    <h1>Departamentos 🚪</h1>
    <table class='table table-hover'>
      <thead>
        <tr>
          <th class="text-center">Número de departamento</th>
          <th>Edificio</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @apartments.each do |apartment| %>
          <tr>
            <td class="text-center"><%= apartment.apartment_number %></td>
            <td class="text-left"><%= link_to apartment.building.name, building_path(apartment.building) %></td>
            <td><%= link_to 'Ver departamento', apartment, class:'btn btn-outline-info text-info' %></td>
            <td><%= link_to 'Editar', edit_apartment_path(apartment), class: "btn btn-outline-warning text-warning" %></td>
            <td><%= link_to 'Eliminar', apartment, class:'btn btn-outline-danger text-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <div class="mb-3 text-end">
        <%= link_to 'Nuevo departamento', new_apartment_path, class: 'btn btn-primary text-white' %>
    </div>
  </div>
</div>

app/views/apartments/new.html.erb
<h1>Nuevo Departamento 🚪</h1>

<%= render 'form', p_apartment: @apartment %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Número de departamento:</strong>
  <%= @apartment.apartment_number %>
</p>

<p>
  <strong>Edificio:</strong>
  <%= @apartment.building.name %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @apartment.building.city %>
</p>

<%= link_to 'Editar departamento', edit_apartment_path(@apartment) %> |
<%= link_to 'Volver', apartments_path %>

app/views/buildings/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(model: building) do |form| %>
      <% if building.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

          <ul>
            <% building.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label "Nombre", class:'form-label' %>
        <%= form.text_field :name, class:'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label "Dirección", class:'form-label' %>
        <%= form.text_field :address, class:'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label "Ciudad", class:'form-label' %>
        <%= form.text_field :city, class:'form-control' %>
      </div>

      <div class="mb-3 text-end">
        <%= link_to "Cancelar", buildings_path, class:'btn btn-light mr-3' %>
        <%= form.submit "Registrar", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/buildings/edit.html.erb
<h1>Editar Edificio</h1>

<%= render 'form', building: @building %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-body">
    <h1>Edificios 🏦</h1>
    <table class='table table-hover'>
      <thead>
        <tr>
          <th>ID</th>
          <th>Nombre</th>
          <th>Dirección</th>
          <th>Ciudad</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @buildings.each do |building| %>
          <tr>
            <td><%= building.id %></td>
            <td><%= link_to building.name, building_path(building) %></td>
            <td><%= building.address %></td>
            <td><%= building.city %></td>
            <td><%= link_to 'Ver edificio', building, class:'btn btn-outline-info text-info' %></td>
            <td><%= link_to 'Editar', edit_building_path(building), class: "btn btn-outline-warning text-warning" %></td>
            <td><%= link_to 'Eliminar', building, class:'btn btn-outline-danger text-danger', method: :delete, data: { confirm: '¿Estás seguro que quieres eliminar este edificio?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <div class="mb-3 text-end">
      <%= link_to 'Nuevo edificio', new_building_path, class: 'btn btn-primary text-white' %>
    </div>
  </div>
</div>

app/views/buildings/new.html.erb
<h1>Nuevo edificio</h1>

<%= render 'form', building: @building %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID edificio:</strong>
  <%= @building.id %>
</p>

<p>
  <strong>Nombre edificio:</strong>
  <%= @building.name %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @building.address %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @building.city %>
</p>

<h4 class=mt-4>Departamentos</h4>

<table class='table table-hober'>
  <thead>
    <tr>
      <th class='text-center'>N° Departamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @building.apartments.each do |apartment| %>
      <tr>
        <td class="text-center"><%= apartment.apartment_number %></td>
        <td><%= link_to 'Editar', edit_apartment_path(apartment), class: "btn btn-outline-warning text-warning" %></td>
        <td><%= link_to 'Eliminar', apartment, class:'btn btn-outline-danger text-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="mb-3 text-end">
  <%= link_to 'Volver', buildings_path, class: 'btn btn-light' %>
  <%= link_to 'Editar edificio', edit_building_path(@building), class: 'btn btn-secondary text-white' %> |
</div>

app/views/layouts/_vertical_menu.html.erb
<nav class="vertical-menu col-lg-2 col-md-4 col-sm-0">
  <div class="row">
    <div class="col">
      <h4 class="titulo text-center">
      Edificios 🏢
      </h4>
    </div>
  </div>
  <div class="container">
    <ul>
      <li class="separador mb-1 mt-3">
        <strong>Edificios</strong>
      </li>
      <li>
        <%= link_to buildings_path, class:"option" do %>
          <i class="bi bi-card-checklist"></i>
          Lista de edificios
        <% end %>
      </li>
      <li>
        <%= link_to new_building_path, class:"option" do%>
          <i class="bi bi-plus-circle"></i>
          Crear edificio
        <% end %>
      </li>
      
      <li class="separador mb-1 mt-3">
        <strong>Departamentos</strong>
      </li>
      <li>
        <%= link_to apartments_path, class:"option" do %>
          <i class="bi bi-card-checklist"></i>
          Lista de departamentos
        <% end %>
      </li>
      <li>
        <%= link_to new_apartment_path, class:"option" do%>
          <i class="bi bi-plus-circle"></i>
          Crear departamento
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Edificios</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/vertical_menu" %>
    <div class="container pt-5 col-lg-10 offset-lg-2 col-md-8 offset-md-4 col-sm-12">
      <%= yield %>
    </div>
  </body>
</html>